modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="mythicgear" #mandatory
version="1.19.2-1.0.0" #mandatory
displayName="Mythic Gear" #mandatory
logoFile="examplemod.png" #optional
credits="" #optional
authors="Jaydizzle" #optional
description='''
This mod adds things. Important things.
'''
[[dependencies.examplemod]] #optional
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="[36,)" #mandatory
ordering="NONE"
side="BOTH"
[[dependencies.examplemod]]
modId="mythicgear"
mandatory=true
versionRange="[1.19.2)"
ordering="NONE"
side="BOTH"